#By using single commands, we can build, start, log, and stop a group of cooperating microservices running as Docker containers.
version: '2.1'
services:
  #The name of the microservice.
  #This will also be the hostname of the container in the internal Docker network.
  product:
    #directive that specifies where to find the Dockerfile that was used to build the Docker image
    build: microservices/product-service
    mem_limit: 512m
    #environment variables that will be set up for the container.
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  recommendation:
    build: microservices/recommendation-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  review:
    build: microservices/review-service
    mem_limit: 512m
    environment:
      - SPRING_PROFILES_ACTIVE=docker
  product-composite:
    build: microservices/product-composite-service
    mem_limit: 512m
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker